### PR TITLE
Release @google-cloud/asset v0.1.0

### PR DESCRIPTION
**Pull request by jkwlui**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
This is weird.  Where's the version bump in package.json?

**Comment by kinwa91** [comment]
weird indeed!

**Comment by kinwa91** [comment]
Oh. when the library is initialized it starts at v0.1.0 - so no version bump is needed - just the changelog here.

**Review by JustinBeckwith — APPROVED** [review]

**Comment by kinwa91** [comment]
Release is at https://github.com/googleapis/nodejs-asset/releases/tag/v0.1.0

**Pull request merged**
