### PR TITLE
refactor(samples): convert sample tests from ava to mocha

### PR DESCRIPTION
**Pull request by nareshqlogic**
Fixes convert all sample tests from ava to mocha [#2865](https://github.com/googleapis/google-cloud-node/issues/2865) (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@nareshqlogic I invited you to the `googleapis` org so your tests run automatically.  Can you please check your email and accept those invitations?  Thanks!

**Comment by nareshqlogic** [comment]
Hi @JustinBeckwith,

I didn't get email regarding googleapis org.

**Comment by JustinBeckwith** [comment]
I tried sending it again *scratches head* what happens if you visit https://github.com/googleapis?

**Comment by JustinBeckwith** [comment]
(also looks like you need to `npm run fix`)

**Comment by nareshqlogic** [comment]
If I visit  https://github.com/googleapis then I will be able to see googleapis and as well as view invitation link. After clicking on link it moves on two_factor_authentication. Here I am not able to set country code for India. Will it work without two_factor_authentication?

**Comment by JustinBeckwith** [comment]
Nope, you need to have two factor auth enabled. Can you use the Google Authenticator app for android or iOS?

**Comment by nareshqlogic** [comment]
Hi @JustinBeckwith,  
Now I have enabled two factor auth and I fix the lint issue.

**Pull request merged**
